# LUMIN.AI Development Environment - Minimal Version
# Simplified Docker Compose configuration for stable development setup

services:
  # Main development environment container
  lumin-dev-environment:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
        NODE_VERSION: "18"
        USERNAME: "lumin-dev"

    container_name: lumin-ai-dev
    command: sleep infinity

    # Volume mounts for persistent development
    volumes:
      # Project source code
      - ../:/workspace:cached
      # Persistent Python package cache
      - lumin-python-packages:/home/lumin-dev/.cache/pip

    # Port mapping (must match devcontainer.json forward ports)
    ports:
      - "${DEV_SERVER_PORT:-3000}:3000"   # React development server
      - "${API_SERVER_PORT:-8000}:8000"   # FastAPI/Flask service
      - "${JUPYTER_PORT:-9000}:9000"      # Jupyter notebook
      # Note: MongoDB is not directly exposed to host by default for security

    # Environment variables
    env_file:
      - .env

    # Configure network for service communication
    networks:
      - lumin-network

  # MongoDB service for data storage
  governance-db:
    image: mongo:6.0
    container_name: lumin-governance-db
    restart: unless-stopped

    # Store data outside container for persistence
    volumes:
      - governance-data:/data/db
      - ./init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro

    # Environment variables for DB setup
    env_file:
      - .env

    # Internal port only - not exposed to host by default for security
    # Access MongoDB through the lumin-dev-environment container for better security
    # Uncomment below lines if direct host access is required for development
    # ports:
    #   - "${MONGODB_PORT:-27017}:27017"

    # Configure network
    networks:
      - lumin-network

# Persistent volumes
volumes:
  governance-data:
    # Data persists even when containers are removed
  lumin-python-packages:
    # Package cache for faster builds

# Network for container communication
networks:
  lumin-network:
    driver: bridge
